In [2]:
from torchvision.transforms import ToTensor

from convolutional_model import ConvolutionalModel
from emotionDetectionDataset import EmotionDetectionDataset
from torch_train import *

In [3]:
ROOT_PATH = 'dataset'
MODEL_SAVE_PATH = './models/model.pth'
config = {'max_epochs': 60, 'batch_size': 64, 'weight_decay': 0.01, 'lr': 0.001}

TRAIN_VAL_SPLIT = 0.75

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
train, test = EmotionDetectionDataset(root=ROOT_PATH, train=True, transform=ToTensor()), EmotionDetectionDataset(
    root=ROOT_PATH, train=False, transform=ToTensor())

In [5]:
train_data_loader, val_data_loader, test_data_loader = prepare_dataset(train, test, config['batch_size'],
                                                                       train_val_split=TRAIN_VAL_SPLIT)

In [6]:
model = ConvolutionalModel().to(device)

In [7]:
# ucitavanje saveanog modela
model.load_state_dict(torch.load('./models/model.pth', map_location=device))

<All keys matched successfully>

In [6]:
history = train_torch_model(model, train_data_loader, val_data_loader, config, device=device, write_to_tensorboard=True, model_save_path=MODEL_SAVE_PATH)

Epoch 0, train loss=0.029596904292702675, train accuracy=0.24071149916403492
Epoch 0, validation loss=0.026153799146413803, validation accuracy=0.3479169569457991
Epoch 1, train loss=0.02386166714131832, train accuracy=0.4141278097715029
Epoch 1, validation loss=0.021510979160666466, validation accuracy=0.47707955970461197
Epoch 2, train loss=0.02122112363576889, train accuracy=0.4852312836708155
Epoch 2, validation loss=0.020742930471897125, validation accuracy=0.4878082764386234
Epoch 3, train loss=0.020741483196616173, train accuracy=0.4996749024707412
Epoch 3, validation loss=0.020966844633221626, validation accuracy=0.49226696391249825
Epoch 4, train loss=0.0204464141279459, train accuracy=0.5109604309864388
Epoch 4, validation loss=0.020497895777225494, validation accuracy=0.5004876689424551
Epoch 5, train loss=0.02032097987830639, train accuracy=0.5104031209362809
Epoch 5, validation loss=0.019922522827982903, validation accuracy=0.518183084854396
Epoch 6, train loss=0.020158182

In [8]:
labels = list(train.labels_and_classes.keys())
confusion_matrix, precision_and_recall = evaluate_model(model, test_data_loader, labels=labels, device=device)

Total loss: 0.01744925230741501. Accuracy: 0.5886040679855112
[[ 475.    0.   52.   58.  123.  210.   40.]
 [  69.    0.    9.    4.    6.   19.    4.]
 [ 149.    0.  187.   47.  126.  366.  149.]
 [  35.    0.   33. 1460.   80.   78.   88.]
 [  80.    0.   34.  110.  703.  283.   23.]
 [ 119.    0.   60.   75.  218.  745.   30.]
 [  20.    0.   75.   28.   22.   31.  655.]]
Preciznost klase 0: 0.5015839493136219. Odziv klase 0: 0.49582463465553234
Preciznost klase 1: nan. Odziv klase 1: 0.0
Preciznost klase 2: 0.41555555555555557. Odziv klase 2: 0.1826171875
Preciznost klase 3: 0.819304152637486. Odziv klase 3: 0.8229988726042841
Preciznost klase 4: 0.5500782472613458. Odziv klase 4: 0.570154095701541
Preciznost klase 5: 0.43013856812933027. Odziv klase 5: 0.5974338412189254
Preciznost klase 6: 0.6622851365015167. Odziv klase 6: 0.7882069795427196


C:\Users\gloga\FER\9.semestar\Neuronske mreže\neumre_projekt\torch_train.py:126: RuntimeWarning: invalid value encountered in scalar divide
  precision_i = tp_i / (tp_i + fp_i)


In [9]:
confusion_matrix

array([[ 475.,   69.,  149.,   35.,   80.,  119.,   20.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [  52.,    9.,  187.,   33.,   34.,   60.,   75.],
       [  58.,    4.,   47., 1460.,  110.,   75.,   28.],
       [ 123.,    6.,  126.,   80.,  703.,  218.,   22.],
       [ 210.,   19.,  366.,   78.,  283.,  745.,   31.],
       [  40.,    4.,  149.,   88.,   23.,   30.,  655.]])

In [10]:
precision_and_recall

array([[0.50158395, 0.49582463],
       [       nan, 0.        ],
       [0.41555556, 0.18261719],
       [0.81930415, 0.82299887],
       [0.55007825, 0.5701541 ],
       [0.43013857, 0.59743384],
       [0.66228514, 0.78820698]])